In [4]:
#creating numpy
l = list(range(1,11))
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [6]:
import numpy as np
my_array = np.array(l)
my_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
type(my_array)

numpy.ndarray

In [1]:
#my_array.shape()

In [9]:
for i in my_array:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [10]:
# import numpy as np
# my_array=([1,2,3,4],[5,6,7,8])
# my_array2=np.reshape(my_array,(3,2))
# print(my_array2)

In [18]:
import numpy as np
l = list(range(1,11))
my_array = np.array(l)
my_array
my_array1 = np.arange(1,5)
my_array1
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
my_array1 + (2,3,4,5)

array([3, 5, 7, 9])

In [25]:
my_array1 // 2


array([0, 1, 1, 2], dtype=int32)

In [26]:
my_array1 ** 2

array([ 1,  4,  9, 16])

In [27]:
#exponential array becomes exponent to 2
2** my_array1

array([ 2,  4,  8, 16], dtype=int32)

In [30]:
my_array1 **0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [31]:
np.sqrt(my_array1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [32]:
np.log(my_array1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [33]:
np.exp(my_array1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [36]:
#diff methods to calculate sum of the array
my_array1.sum()
np.sum(my_array1)
sum(my_array1)

10

In [45]:
#diff methods to calculate size of the array
len(my_array1)
my_array1.size

4

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [59]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [60]:
np.random.rand(2,3)

array([[0.99200849, 0.36403383, 0.52092214],
       [0.08513432, 0.36636961, 0.56311126]])

In [62]:
np.random.rand(2,3)*100

array([[96.83536942, 46.51747908,  6.2453843 ],
       [44.5566181 , 18.56759779, 86.13307868]])

In [66]:
np.random.randint(8, size = (2,3))

array([[0, 5, 2],
       [5, 0, 6]])

In [19]:
import numpy as np
a = list(range(1,13))
l = np.array(a)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
import numpy as np
l = l.reshape(3,4)
l

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
l.dtype

dtype('int32')

In [28]:
l.shape

(3, 4)

In [42]:
l.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [33]:
import numpy as np
a = list(range(1,13))
l = np.array(a)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
np.arange(2,8,2)

array([2, 4, 6])

In [32]:
l

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
import numpy as np
np.loadtxt('txt1.txt')

array([129455.,   4578.])

In [62]:
np.genfromtxt('txt1.csv',delimiter = ',')

array([ 45. ,  56. , 666. ,  45. ,  45.4, 499. ])

In [78]:
np.savetxt('txt1.csv',[50,566],delimiter=',')

np.genfromtxt('txt1.csv',delimiter = ',')

array([ 50., 566.])