In [1]:
#loading dataset
from sklearn.datasets import load_iris
iris = load_iris()
x = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print('feature name: ' , feature_names[:10])
print('target names: ' , target_names[:10])
print('first 10 element of x:',x[:10])

feature name:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target names:  ['setosa' 'versicolor' 'virginica']
first 10 element of x: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [2]:
#splitting the dataset
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
x = iris.data
y = iris.target
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state = 1)
print(x_train.shape)
print(x_test.shape)
print(y_test.shape)
print(y_train.shape)

(105, 4)
(45, 4)
(45,)
(105,)


In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
classifier_knn = KNeighborsClassifier(n_neighbors = 3) 
classifier_knn.fit(x_train,y_train)
y_pred = classifier_knn.predict(x_test)
print('accuracy:',metrics.accuracy_score(y_test,y_pred))

accuracy: 0.9777777777777777


In [15]:
# from sklearn.datasets import load_wine
# # wine = load_wine(return_x_y, as_frame)
# print(wine)

In [30]:
import numpy as np
from sklearn import preprocessing 
input_data = np.array([[2.1,-1.9,5.5],[-1.5,2.4,3.5],[0.5,-7.9,5.6],[5.9,2.3,-5.8]])
binarized_data = preprocessing.Binarizer(threshold=0.5).transform(input_data)
print(binarized_data)

[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [31]:
#mean removal
print('Mean:',input_data.mean(axis=0))
print('stddev:',input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print('removed mean:',data_scaled.mean(axis=0))
print('removed std:',data_scaled.std(axis=0))

Mean: [ 1.75  -1.275  2.2  ]
stddev: [2.71431391 4.20022321 4.69414529]
removed mean: [1.11022302e-16 0.00000000e+00 0.00000000e+00]
removed std: [1. 1. 1.]


In [32]:
#scaling
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print(data_scaled_minmax)

[[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


In [8]:
#imputation of missing values
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imp.fit ([[1,2],[np.nan,3],[7,6]])
SimpleImputer()
x = [[np.nan,2],[6,np.nan],[7,6]]
print(imp.transform(x))

[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]


In [18]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan, strategy = 'constant')
imp.fit([[2,3],[np.nan,5],[3,4]])
x = [[np.nan,8],[2,7],[3,np.nan]]
print(imp.transform(x))

[[0. 8.]
 [2. 7.]
 [3. 0.]]


In [28]:
import pandas as pd
import numpy as np
df = pd.DataFrame([['x','y'],[np.nan,'z'],['x','y']])
imp = SimpleImputer(strategy = 'most_frequent')
print(imp.fit_transform(df))

[['x' 'y']
 ['x' 'z']
 ['x' 'y']]
